name: CI - Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validar Pull Request
        run: echo "Pull Request validado correctamente."