name: CI - Backend Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      PORT: 4000

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar servidor
        run: |
          npm start &
          sleep 10

      - name: Verificar API
        run: curl --fail http://localhost:4000/api/health